app/index.js, lib/registry.js
Ensure resolveDevPage url is a string.
Plus Registry.get method checks property existance and returns original value if property contained in registry. Default value otherwise.
=> Ensure resolveDevPage url is a string.

lib/namer.js, tests/namer.spec.js
For issue: https://github.com/2gis/slot/issues/195
=> add className parser for block #195

.gitignore, env.js, lib/injector.js, lib/modulesQuering.js, lib/templateProvider.js, slot/index.js
Исправил JSDoc из-за которого не генерировалась документация для модуля Slot
=> Fix JSDoc issues that affected doc generation

.travis.yml, package.json
Update dependencies
Update travis.yml
=> Support node.js v4.0.0

app/index.js, tests/app.spec.js
Дополнение к https://github.com/2gis/slot/pull/213.
Корректно удаляем куку на сервере.
=> fix cookie removing at server-side

package.json
Should be merged only after tests on the ONLINE-8111
=> Update ua-parser-js upto 0.7.9

cli/templates/common/package.json, cli/templates/common/tasks/manifest.js, gulpy/pot.js, lib/defer.js, lib/expandString.js, package.json
Update lodash version to v3.6.0
Adapt code to that version
=> Switch to lodash v3

package.json
=> Revert "Update async to version 1.5.0"

lib/stuff.js
https://github.com/2gis/slot/pull/229
=> improve extend query function

components/appState/api.js
После https://github.com/2gis/slot/pull/233 решили убрать всю логику связанную с implicitChanges и finalizer.
=> Remove implicit changes and finalizer

gulpy/recipes/templates.js, gulpy/snippets/templatify.js
Added templatify path customization.
Minor non-breaking change.
=> Add templatify path customization

lib/request.js, package.json
=> Revert "remove-lib/request"

gulpy/recipes/po2json.js, i18n/tasks/po2json.js, package.json, slot/index.js
Убираем часть захардкоженного кода в пользу более гибкого.
=> Fix i18n globpath hardcode and req abort hardcore

components/stateTracker.js, package.json
Added an opportunity to determine that new state of app obtained with the use of historyApi popstate method.
=> Add an opportunity to determine history popstate

package.json
1.4.0 has same problems as 1.4.1.
downgrading to initial 1.1.2
=> downgrade morphdom again

components/appState/stateConf.js, package.json
Небольшая оптимизация. Кеширует скомпилированные сео паттерны урлов, чтобы не создавать и не компилировать новый паттерн для каждой ссылки.
=> stateConf seoUrls patterns cache

components/appState/index.js, package.json
Прокидывание notParsed частей url'а в приложение, чтобы оно, например, могло вернуть 404 на плохие url'ы.
=> bad url process

components/appState/index.js, package.json
Оптимизация. Сохранения результатов парсера, для их переиспользования. Чтобы не парсить несколько раз одно и тоже.
=> url multireparsing fix

components/appState/index.js, package.json
=> fix actualize query string

env.js, package.json
=> Made interoperable require default #271
